name: ChatGPT CodeReviewer

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@v1.0.21
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANGUAGE: javascript
          REVIEW_COMMENT_LGTM: false
